---
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: instance
    image: centos:7
provisioner:
  name: ansible
  config_options:
    diff:
      always: true
  lint:
    name: ansible-lint
scenario:
  name: default
  check_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - check
    - destroy
verifier:
  name: goss
  lint:
    name: yamllint
